// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gooukwghamebsetobzwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdvb3Vrd2doYW1lYnNldG9iendhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwOTU2NDUsImV4cCI6MjA3MzY3MTY0NX0.XQ03uIBLnw5Ua_NDT8naGNdkvZd6g_uow6lbFVTk43E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});